apiVersion: v1
kind: PersistentVolume
metadata:
  name: consultoria-pv-upload-files-test
  namespace: test
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteOnce
  #persistentVolumeReclaimPolicy: Delete
  storageClassName: sc-consultoria
  nfs:
    server: 10.48.82.2
    path: /consultoria/uploads/test

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consultoria-pvc-upload-files-test
  namespace: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: sc-consultoria
  resources:
    requests:
      storage: 1Ti