name: Deploy Application UploadFile

on:
  push:
    branches: [main]
  workflow_dispatch: 

jobs:
  CI:
    name: "Processo de CI"
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout do Codigo
        uses: actions/checkout@v4
        
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build e Push da imagem para docker hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: | 
            iuripetrola/app_upload_file:v${{github.run_number}}
            iuripetrola/app_upload_file:latest