name: Deploy Application UploadFile

on:
  push:
    branches: [main]
  workflow_dispatch: 

jobs:
  CI:
    name: "Processo de CI"
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout do Codigo
        uses: actions/checkout@v4
        
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build e Push da imagem para docker hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: | 
            iuripetrola/app_upload_file:v${{github.run_number}}
            iuripetrola/app_upload_file:latest
  CD:
    name: "Processo de CD"
    runs-on: ubuntu-22.04
    needs: CI
    steps:
      - name: Checkout do Codigo
        uses: actions/checkout@v4
      
      - name: Configuraçao do contexto do kubernetes
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v5
        with:
          manifests: |
            ./deployment.yaml
          images: |
            iuripetrola/app_upload_file:v${{github.run_number}}