name: Workflow call

on: 
    workflow_dispatch:
      inputs:
        ambiente:
          type: choice
          default: "desenvolvimento"
          required: true
          description: "Ambiende do deploy"
          options:
            - desenvolvimento
            - homologacao
            - producao

jobs:
    CI:
      runs-on: ubuntu-latest
      steps:
          - name: Build de Imagem Docker
            run: echo "Execução do comando de docker build"
          - name: Execução de Testes de Software
            run: echo "Aqui eu executo o teste de software"
          - name: Publicando a Release
            run: echo "Publicação da Relase final"
    
    CD:
      needs: [CI]
      uses: iuri-petrola/app_Upload_File/.github/workflows/workflow-call-CD.yaml@main
      with:
        ambiente: ${{inputs.ambiente}}