name: Workflow call-CD

on: 
    workflow_call:
      #secrets:
      #  ambiente:
      #    required: true
      #    description: "Ambiente de deploy" 

      #inputs:
      #  ambiente:
      #    type: string
      #    default: "desenvolvimento"
      #    required: true
      #   description: "Ambiente do deploy" 

jobs:
    deploy-kubernetes:
      runs-on: ubuntu-latest
      steps:
        - name: Deploy no ambiente
          run: echo "Executando o deploy no ambiente de ${{secrets.AMBIENTE}}"
        - name: Curl no ambiente
          run: "curl -X POST https://webhook.site/1105f454-532a-4232-a03b-d906038f80b3 -d '{ ambiente: ${{secrets.AMBIENTE}}}' "