name: Workflow call-CD

on: 
    workflow_call:
      secrets:
        ambiente:
          required: true
          description: "Ambiente de deploy" 

      #inputs:
      #  ambiente:
      #    type: string
      #    default: "desenvolvimento"
      #    required: true
      #   description: "Ambiente do deploy" 

jobs:
    deploy-kubernetes:
      runs-on: ubuntu-latest
      steps:
        - name: Deploy no ambiente
          run: echo "Executando o deploy no ambiente de ${{secrets.ambiente}}"